---
- name: Update attachments of vrfs
  ansible.builtin.set_fact:
    update_list: "{{ update_list + update }}"
  loop: "{{ vrfs }}"
  loop_control:
    label: "{{ item.vrf_name }}"
    index_var: i
  vars:
    update_list: []
    update:
      - path: vrfs[{{ i }}].attach
        value: "{{ vrf_attach_group[item.attach_group] }}"
  tags:
    - vrf
    - overlay

- name: Update VRF config
  ansible.utils.update_fact:
    updates: "{{ update_list }}"
  register: updated_vrfs
  tags:
    - vrf
    - overlay

- name: Current vrf config
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ updated_vrfs.vrfs }}"
  loop_control:
    label: "{{ item.vrf_name }}"
  tags:
    - vrf
    - overlay

- name: Create vrfs
  cisco.dcnm.dcnm_vrf:
    fabric: "{{ fabric.name }}"
    # state: overridden
    config: "{{ updated_vrfs.vrfs }}"
  tags:
    - vrf
    - overlay
